### ISSUE TITLE
ExtensionDictionary空引用

### ISSUE THREAD

**Issue by wsky** [codesharp/cooper#102]
``` c#
private IDictionary<string, string> Parse()
        {
            return string.IsNullOrWhiteSpace(this._extensions)
                ? new Dictionary<string, string>()
                : _serializer.JsonDeserialize<IDictionary<string, string>>(this._extensions);
        }
```

this._extensions为空时，JsonDeserialize将为Null

**Comment by wsky** [comment]
``` c#
(xxx?xx:xx)?? new Dictionary<string, string>()
```

**Comment by wsky** [comment]
没考虑已有数据的兼容问题

**Comment by wsky** [comment]
``` c#
private string _extensions { get; set; }
```

字符串未赋值是为null

导致component映射也为null

**Comment by wsky** [comment]
``` c#
public ExtensionDictionary()
        {
            this._extensions = string.Empty;
        }
```

至少这样

**Comment by tangxuehua** [comment]
Fixed, 两重防线：
1. this._extensions = string.Empty;
2. 使用component的实体在get component时判断是否为空，如果为空，则进行实例化；
   related commit urls:
   https://github.com/codesharp/cooper/commit/170a982da8f2e7735a1239b1e5d40ebc304c01eb
   https://github.com/codesharp/cooper/commit/0e2da372b4bc9f16ad1535100d09b1c7c2585e55

**Comment by wsky** [comment]
@tangxuehua 少数设计才需要这样考虑，大多数时候避免不必要的防御编码
