### ISSUE TITLE
hybrid版本需要同时支持pc/mobi borrower的刷新，按url显示UI

### ISSUE THREAD

**Issue by wsky** [codesharp/cooper#19]

**Comment by wsky** [comment]
注意pageshow pageinit的选择

**Comment by tangxuehua** [comment]
hybrid版本目前已支持pc/mobile borrower的刷新，所有页面需要的参数都放在url中；数据显示的逻辑放在pagebeforeshow事件响应函数中完成，这样做确保刷新页面也能重新根据参数得到需要显示的数据。
