### ISSUE TITLE
离线模式和未登录时的刷新处理

### ISSUE THREAD

**Issue by wsky** [codesharp/cooper#26]
native将提供是否有网络的判断接口

**Comment by wsky** [comment]
刷新时要有loading效果 使用jqmobile的api

**Comment by tangxuehua** [comment]
已经为taskListPage,taskPage的刷新按钮增加了loading的效果

**Comment by wsky** [comment]
修正好了自己把issue close掉

**Comment by tangxuehua** [comment]
主要是这个issue中提到的判断是否有网络的功能还没实现，所以还没关闭。用jquery mobile能判断吗？好像没找到判断的接口。

**Comment by wsky** [comment]
先mock一个 到时候要native支持

**Comment by tangxuehua** [comment]
已增加了一个mock 函数用来判断网络是否可用。
